### ISSUE TITLE
Bad MaxTeamScore values break the core.

### ISSUE THREAD

**Issue by CacoFFF** [CacoFFF/SiegeIV-UT99#6]
If zero or negative it should automatically set to 20 as default.

**Comment by Chamberly** [comment]
I was messing with that and got a nasty result.

What it looks like when it have a MaxTeamScore of 0 in game: https://i.gyazo.com/e2f402580b7950fde6482e8783d6293c.png
Other cause: Shooting at the core will self-destruct, If you are in the explosion range and get killed by it, you spawn as a spectator instead.

It does work with a minimum of 1.

**Comment by CacoFFF** [comment]
Fixed
